apiVersion: v1
kind: LimitRange
metadata:
  name: compute-resources
  namespace: vote
spec:
  limits:
  - type: Pod
    default:
      cpu: 500m
      memory: 256Mi
    defaultRequest:
      cpu: 200m
      memory: 128Mi
    max:
      cpu: "1"
      memory: 512Mi
    min:
      cpu: 100m
      memory: 64Mi
    