apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
  namespace: vote
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi  
    pods: "10"
    persistentvolumeclaims: "5"
    requests.storage: 5Gi
    configmaps: "10"
    services: "5"
    