apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ghost-stack.fullname" . }}-ghost
  labels:
    {{- include "ghost-stack.labels" . | nindent 4 }}
type: Opaque
stringData:
  GHOST_USERNAME: {{ .Values.ghost.username | quote }}
  GHOST_PASSWORD: {{ .Values.ghost.password | quote }}
  GHOST_EMAIL: {{ .Values.ghost.email | quote }}