apiVersion: apps/v1
kind: Deployment
metadata:
  name: observer-scheduler
spec:
  replicas: 5
  selector:
    matchLabels:
      app: observer
  template:
    metadata:
      labels:
        app: observer
    spec:
      containers:
      - name: nginx
        image: nginx:1.21
        resources:
          requests:
            cpu: 100m
            memory: 128Mi