apiVersion: v1
kind: Pod
metadata:
  name: trois-writers
spec:
  containers:
  - name: writer-logs
    image: busybox
    command:
    - sh
    - -c
    - |
      while true; do
        echo "$(date): Log d'application" >> /shared/app.log
        sleep 3
      done
    volumeMounts:
    - name: shared-volume
      mountPath: /shared
  
  - name: writer-metrics
    image: busybox
    command:
    - sh
    - -c
    - |
      while true; do
        echo "$(date): CPU=$(($RANDOM % 100))% MEM=$(($RANDOM % 100))%" >> /shared/metrics.txt
        sleep 5
      done
    volumeMounts:
    - name: shared-volume
      mountPath: /shared
  
  - name: writer-events
    image: busybox
    command:
    - sh
    - -c
    - |
      while true; do
        echo "$(date): Événement_$(($RANDOM % 1000))" >> /shared/events.log
        sleep 7
      done
    volumeMounts:
    - name: shared-volume
      mountPath: /shared
  
  - name: reader-all
    image: busybox
    command:
    - sh
    - -c
    - |
      while true; do
        echo "=== RÉSUMÉ DES FICHIERS ==="
        echo "Logs: $(wc -l < /shared/app.log 2>/dev/null || echo 0) lignes"
        echo "Metrics: $(wc -l < /shared/metrics.txt 2>/dev/null || echo 0) lignes"
        echo "Events: $(wc -l < /shared/events.log 2>/dev/null || echo 0) lignes"
        echo "=========================="
        sleep 10
      done
    volumeMounts:
    - name: shared-volume
      mountPath: /shared
  
  volumes:
  - name: shared-volume
    emptyDir: {}