apiVersion: v1
kind: Service
metadata:
  labels:
    app: result-ui
  name: result-ui
spec:
  type: ClusterIP
  ports:
    - name: "result-ui-service"
      port: 5000
      targetPort: 80
  selector:
    app: result-ui
