apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote
  name: vote
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
        - image: mohamed1780/vote:v1
          name: vote
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: vote
